export enum Signal {
  Buy = "buy",
  Hold = "hold",
  Sell = "sell",
}

export enum MarketType {
  usdt = "usdt",
  irt = "irt",
}
export const periodPoint = 30;
export const resolution = 60; //60, 180, 240, 360, 720, D, 2D, 3D

export const periodSMA = 720; //number of time units (e.g., days) , 7 days * 24 hours/day = 168 periods
export const periodBB = 720; // the number of time units
export const stdDevMultiplier = 2; //the number of standard deviations used to calculate the width of the Bollinger Bands

export const shortPeriod = 26; //the shorter time period used to calculate the Exponential Moving Average
export const longPeriod = 12; //the longer time period used to calculate the Exponential Moving Average
export const signalPeriod = 9; //the time period used to calculate the signal line

export const periodRSI = 14;
export const overboughtThreshold = 70;
export const oversoldThreshold = 30;

export const symboles = [
  "btc",
  "eth",
  "etc",
  "doge",
  "ada",
  "bch",
  "ltc",
  "bnb",
  "eos",
  "xlm",
  "xrp",
  "trx",
  "uni",
  "link",
  "dai",
  "dot",
  "shib",
  "aave",
  "ftm",
  "matic",
  "axs",
  "mana",
  "sand",
  "avax",
  "usdc",
  "gmt",
  "mkr",
  "sol",
  "atom",
  "grt",
  "bat",
  "near",
  "ape",
  "qnt",
  "chz",
  "xmr",
  "egala",
  "algo",
  "hbar",
  "1inch",
  "yfi",
  "flow",
  "snx",
  "enj",
  "crv",
  "fil",
  "wbtc",
  "ldo",
  "dydx",
  "apt",
  "mask",
  "comp",
  "bal",
  "lrc",
  "lpt",
  "ens",
  "sushi",
  "api3",
  "one",
  "glm",
  "dao",
  "cvc",
  "nmr",
  "storj",
  "snt",
  "ant",
  "zrx",
  "slp",
  "egld",
  "imx",
  "blur",
  "100k_floki",
  "1b_babydoge",
  "1m_nft",
  "1m_btt",
  "t",
  "celr",
  "arb",
  "magic",
  "gmx",
  "band",
  "cvx",
  "ton",
  "ssv",
  "mdt",
  "omg",
  "wld",
  "rdnt",
  "jst",
  "bico",
  "rndr",
  "woo",
  "skl",
  "gal",
  "agix",
  "fet",
];
